### ISSUE TITLE
同一手机号, 使用不同算法会导致查询结果不一致

### ISSUE THREAD

**Issue by YAOAORAN** [EeeMt/phone-number-geo#1]
版本描述:
version:1.0.5-202004
jdk:1.8.0_131

问题截图(含堆栈信息):
![image](https://user-images.githubusercontent.com/28530698/81380413-74648a00-913d-11ea-866d-43b6c2f03322.png)
![image](https://user-images.githubusercontent.com/28530698/81380530-a970dc80-913d-11ea-9610-6a898b49fb59.png)

**Comment by EeeMt** [comment]
感谢, 已修复
