### ISSUE TITLE
[建议] 建议把运营商中文名称也写上

### ISSUE THREAD

**Issue by chengaopan** [EeeMt/phone-number-geo#13]
例如:
https://github.com/ls0f/phone/blob/master/phone/phone.py
![image](https://github.com/EeeMt/phone-number-geo/assets/18641281/0f0a27cf-afc5-4286-a912-6475c7d27bb9)

**Comment by EeeMt** [comment]
这个我认为是属于展示层的东西, 做得好一点就是多语言支持. 这个包主要提供的是数据能力, 展示相关的不是很有必要
