### ISSUE TITLE
缺少 getter 方法

### ISSUE THREAD

**Issue by dugenkui03** [EeeMt/phone-number-geo#4]
https://github.com/EeeMt/phone-number-geo/blob/c43c37c923ab08e7b6b6707b08b7dcedd3cdd408/src/main/java/me/ihxq/projects/pna/ISP.java#L29

没有 getter 方法

**Comment by EeeMt** [comment]
这个值拿来干啥, 不就是应该封装掉, 隐藏这些细节的吗

**Comment by dugenkui03** [comment]
> 这个值拿来干啥, 不就是应该封装掉, 隐藏这些细节的吗

不能读取、这个字段存在的意义是什么

**Comment by EeeMt** [comment]
> > 这个值拿来干啥, 不就是应该封装掉, 隐藏这些细节的吗
> 
> 不能读取、这个字段存在的意义是什么

和数据文件里的运营商标识对应啊, 对于调用方, 知道是哪个运营商就够了, 不需要关心怎么来的(这不就是封装的意义吗)
