### ISSUE TITLE
频繁的gc

### ISSUE THREAD

**Issue by tiffanychen1993** [EeeMt/phone-number-geo#5]
使用定时任务每隔1秒调用一次的时候会导致频繁的FGC
@Scheduled(cron = " */1 * * * * ?")
  public void test() {
    log.info("===test===");
    String number ="18625059406";
    PhoneNumberInfo phoneNumberInfo = new PhoneNumberLookup().lookup(number).orElse(null);
    if (ObjectUtils.isNotEmpty(phoneNumberInfo)) {
      log.info(phoneNumberInfo.getAttribution().getProvince() + phoneNumberInfo.getAttribution().getCity());
    }

![image](https://user-images.githubusercontent.com/8486775/99246621-9489aa00-2840-11eb-804e-46c4a2ea0cb1.png)

![image](https://user-images.githubusercontent.com/8486775/99246862-f34f2380-2840-11eb-89d5-8b0649737cff.png)

![image](https://user-images.githubusercontent.com/8486775/99246950-1da0e100-2841-11eb-8b74-dc18ddbcea4d.png)

这个init方法中没有释放资源，请问是这个原因导致的吗？

**Comment by EeeMt** [comment]
确实忘了释放那个inputStream, 不过那个InputStream也只是持有一个文件句柄, 不关闭也不会占用多少内存(依然应该关闭).
建议把堆dump下来分析

**Comment by xsgwork** [comment]
new PhoneNumberLookup()初始化太占资源了吧，弄成静态对象试试

**Comment by EeeMt** [comment]
> new PhoneNumberLookup()初始化太占资源了吧，弄成静态对象试试

不频繁new的话占用资源很少的, new出来的实例放静态变量或者成员变量, 不要每次调用都new一个.
