### ISSUE TITLE
win10下报错：content format error

### ISSUE THREAD

**Issue by itisi00** [EeeMt/phone-number-geo#7]
测试号码：13333333333.
然后其他号码还乱码：
"attribution": {
      "province": "璐靛窞",
      "city": "璐甸槼",
      "zipCode": "550000",
      "areaCode": "0851"
    },

**Comment by EeeMt** [comment]
麻烦把具体的场景说一下吧， 哪个版本， 哪个语言环境， ide还是命令行， 等等

**Comment by EeeMt** [comment]
若能复现, 麻烦反馈一下哈. 如果不能, 那就当作运行环境问题了
