### ISSUE TITLE
急急急！！！！ 异常 192 195 开头号码 无法识别报异常

### ISSUE THREAD

**Issue by huyongjian7** [EeeMt/phone-number-geo#8]
@
phone-number-geo/phone.dat 文件乱码 代码 函数 initData
 try (InputStream inputStream = PhoneNumberGeo.class.getClassLoader().getResourceAsStream(PHONE_DAT_FILE_PATH)) {

**Comment by EeeMt** [comment]
报什么异常， 找不到的话就是库里没有数据

**Comment by EeeMt** [comment]
无法根据提供的信息复现, 请提供更多的信息. issue先关了, 有问题再提就是了
