### ISSUE TITLE
更换 phone.dat

### ISSUE THREAD

**Issue by joinzyh** [EeeMt/phone-number-geo#9]
亲，更换最新版 phone.dat，只需要把源码目录下 得 phone.dat更换了，程序不需要改动吧？

**Comment by EeeMt** [comment]
对的

发自我的iPhone

在 2021年6月23日，09:39，joinzyh ***@***.***> 写道：

﻿

亲，更换最新版 phone.dat，只需要把源码目录下 得 phone.dat更换了，程序不需要改动吧？

**Comment by EeeMt** [comment]
已更新 83c33d4735281c46695d5f6506f8e895a6c3503f
